### PR TITLE
Fixes for newer rust

### PR DESCRIPTION
**Pull request by lilydjwg**
After the fix (robo9k/rust-magic-sys#7) for rust-magic-sys, it's time to fix rust-magic :-)

### CODE REVIEW

**Comment by robo9k** [comment]
I've split your pull request into separate commits, but did not really change anything besides that, so thanks!
Furthermore I had to use nightly `rustc` for the `Path` → `OsStr` → `CString` conversion for Travis being happy.

**Comment by lilydjwg** [comment]
Hi, https://crates.io/crates/magic didn't get updated?

**Comment by robo9k** [comment]
My bad, thought I had `cargo publish` enabled for tagged (i.e. c4baac81962fd77644b1cfea6cf001f1720294da) Travis builds. Published a new version manually ([`0.8.0`](https://crates.io/crates/magic/0.8.0)).

**Comment by lilydjwg** [comment]
Thanks!

**Pull request closed without merging**
